import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import AuthProvider from "../context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sanity E-Sports",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <AuthProvider>
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main className="mx-auto mt-10">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
        </AuthProvider>
  );
}
