import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const helvetica = localFont({
  src: [
    {
      path: "../../fonts/helvetica/HelveticaNowDisplay-Thin.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../fonts/helvetica/HelveticaNowDisplay-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../fonts/helvetica/HelveticaNowDisplay-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../fonts/helvetica/HelveticaNowDisplay-Bold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../fonts/helvetica/HelveticaNowDisplay-ExtraBold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../fonts/helvetica/HelveticaNowDisplay-Black.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../fonts/helvetica/HelveticaNowDisplay-ExtBlk.woff2",
      weight: "900",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Sanity Esports",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={helvetica.className}>
        <Navbar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
